/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/trials/{nct_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stored Trial
         * @description The cached record behind a citation, for the frontend's record viewer. Read-only: it never
         *     calls ClinicalTrials.gov, so it shows the record the excerpt check ran against.
         */
        get: operations["stored_trial_api_trials__nct_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visualize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Visualize */
        post: operations["visualize_api_visualize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Channel */
        Channel: {
            /** Field */
            field: string;
            /**
             * Scale
             * @default linear
             * @enum {string}
             */
            scale: "linear" | "log";
            /**
             * Type
             * @enum {string}
             */
            type: "quantitative" | "nominal" | "ordinal" | "temporal";
        };
        /** ChartVisualization */
        ChartVisualization: {
            /** Data */
            data: components["schemas"]["Row"][];
            /** Encoding */
            encoding: {
                [key: string]: components["schemas"]["Channel"];
            };
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bar_chart" | "grouped_bar_chart" | "histogram" | "scatter_plot" | "time_series";
        };
        /** CheckError */
        CheckError: {
            /** Check */
            check: string;
            /** Message */
            message: string;
        };
        /** Citation */
        Citation: {
            /** Excerpt */
            excerpt: string | null;
            /** Field */
            field: string;
            /** Nct Id */
            nct_id: string;
        };
        /** ClarificationMeta */
        ClarificationMeta: {
            /** Assumptions */
            assumptions: string[];
            filters: components["schemas"]["Filters"];
            /** Missing */
            missing: ("drug_name" | "condition" | "sponsor")[];
            /** Notes */
            notes: string[];
            /**
             * Source
             * @constant
             */
            source: "clinicaltrials.gov";
        };
        /** ClarificationResponse */
        ClarificationResponse: {
            meta: components["schemas"]["ClarificationMeta"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "clarification_needed";
            /** Trials */
            trials: {
                [key: string]: components["schemas"]["TrialSummary"];
            };
            /** Visualization */
            visualization: null;
        };
        /** Cohort */
        Cohort: {
            /** Filters */
            filters: {
                [key: string]: string | number;
            };
            /** Label */
            label: string;
        };
        /** DegradedMeta */
        DegradedMeta: {
            /** Assumptions */
            assumptions: string[];
            /** Errors */
            errors: components["schemas"]["CheckError"][];
            filters: components["schemas"]["Filters"];
            /** Notes */
            notes: string[];
            /**
             * Source
             * @constant
             */
            source: "clinicaltrials.gov";
        };
        /** DegradedResponse */
        DegradedResponse: {
            meta: components["schemas"]["DegradedMeta"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "degraded";
            /** Trials */
            trials: {
                [key: string]: components["schemas"]["TrialSummary"];
            };
            /** Visualization */
            visualization: null;
        };
        /** Edge */
        Edge: {
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Nct Ids */
            nct_ids: string[];
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Trial Count */
            trial_count: number;
        };
        /**
         * ErrorDetail
         * @description The body of a 404 or 502 (SCHEMAS.md §1, §6). A 422 uses FastAPI's own validation body.
         */
        ErrorDetail: {
            /** Detail */
            detail: string;
        };
        /** Exclusion */
        Exclusion: {
            /** Count */
            count: number;
            /** Rule */
            rule: string;
        };
        /** Filters */
        Filters: {
            /** Inferred */
            inferred: {
                [key: string]: string | number;
            };
            /** Stated */
            stated: {
                [key: string]: string | number;
            };
        };
        /** Grouping */
        Grouping: {
            /** Dimension */
            dimension: string;
            /** Series */
            series: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Interpretation */
        Interpretation: {
            /** Cohorts */
            cohorts: components["schemas"]["Cohort"][] | null;
            /** Dimension */
            dimension: string;
            /** Intent */
            intent: string;
        };
        /** NetworkData */
        NetworkData: {
            /** Edges */
            edges: components["schemas"]["Edge"][];
            /** Nodes */
            nodes: components["schemas"]["Node"][];
        };
        /** NetworkEncoding */
        NetworkEncoding: {
            /** Edges */
            edges: {
                [key: string]: components["schemas"]["Channel"];
            };
            /** Nodes */
            nodes: {
                [key: string]: components["schemas"]["Channel"];
            };
        };
        /** NetworkVisualization */
        NetworkVisualization: {
            data: components["schemas"]["NetworkData"];
            encoding: components["schemas"]["NetworkEncoding"];
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "network_graph";
        };
        /** NoResultsMeta */
        NoResultsMeta: {
            /** Assumptions */
            assumptions: string[];
            filters: components["schemas"]["Filters"];
            /** Not Found */
            not_found: string[];
            /** Notes */
            notes: string[];
            /**
             * Source
             * @constant
             */
            source: "clinicaltrials.gov";
        };
        /** NoResultsResponse */
        NoResultsResponse: {
            meta: components["schemas"]["NoResultsMeta"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "no_results";
            /** Trials */
            trials: {
                [key: string]: components["schemas"]["TrialSummary"];
            };
            /** Visualization */
            visualization: null;
        };
        /** Node */
        Node: {
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "drug" | "sponsor" | "condition";
            /** Id */
            id: string;
            /** Is Anchor */
            is_anchor: boolean;
            /** Label */
            label: string;
            /** Nct Ids */
            nct_ids: string[];
            /** Trial Count */
            trial_count: number;
        };
        /** OkMeta */
        OkMeta: {
            /** Assumptions */
            assumptions: string[];
            /** Citation Cap */
            citation_cap: number;
            /** Excluded */
            excluded: components["schemas"]["Exclusion"][];
            filters: components["schemas"]["Filters"];
            grouping: components["schemas"]["Grouping"];
            interpretation: components["schemas"]["Interpretation"];
            /** Notes */
            notes: string[];
            pruning: components["schemas"]["Pruning"] | null;
            /** Sample */
            sample: components["schemas"]["SampleEntry"][];
            sort: components["schemas"]["Sort"];
            /**
             * Source
             * @constant
             */
            source: "clinicaltrials.gov";
            /** Time Granularity */
            time_granularity: "year" | null;
            top_n: components["schemas"]["TopN"] | null;
            /** Units */
            units: {
                [key: string]: string;
            };
        };
        /** OkResponse */
        OkResponse: {
            meta: components["schemas"]["OkMeta"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "ok";
            /** Trials */
            trials: {
                [key: string]: components["schemas"]["TrialSummary"];
            };
            /** Visualization */
            visualization: components["schemas"]["ChartVisualization"] | components["schemas"]["NetworkVisualization"];
        };
        /**
         * Phase
         * @enum {string}
         */
        Phase: "NA" | "EARLY_PHASE1" | "PHASE1" | "PHASE2" | "PHASE3" | "PHASE4";
        /** Pruning */
        Pruning: {
            /** Edges Removed */
            edges_removed: number;
            /** Fallback Used */
            fallback_used: boolean;
            /** Min Edge Weight */
            min_edge_weight: number;
            /** Nodes Removed */
            nodes_removed: number;
            /** Top N Nodes */
            top_n_nodes: number;
        };
        /**
         * Row
         * @description One chart row. Its dimension fields vary by aggregator, so extra fields are allowed.
         */
        Row: {
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Nct Ids */
            nct_ids: string[];
            /** Trial Count */
            trial_count: number;
        } & {
            [key: string]: unknown;
        };
        /** SampleEntry */
        SampleEntry: {
            /** Capped */
            capped: boolean;
            /** Cohort */
            cohort: string | null;
            /** Fetched */
            fetched: number;
            /** Total */
            total: number;
        };
        /** Sort */
        Sort: {
            /** Field */
            field: string;
            /**
             * Order
             * @enum {string}
             */
            order: "asc" | "desc" | "canonical";
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "ACTIVE_NOT_RECRUITING" | "COMPLETED" | "ENROLLING_BY_INVITATION" | "NOT_YET_RECRUITING" | "RECRUITING" | "SUSPENDED" | "TERMINATED" | "WITHDRAWN" | "AVAILABLE" | "NO_LONGER_AVAILABLE" | "TEMPORARILY_NOT_AVAILABLE" | "APPROVED_FOR_MARKETING" | "WITHHELD" | "UNKNOWN";
        /**
         * StoredTrial
         * @description `GET /api/trials/{nct_id}`: a cited trial's record as cached now, which a later
         *     fetch may have replaced since the citation was checked (SCHEMAS.md §6).
         */
        StoredTrial: {
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Nct Id */
            nct_id: string;
            /** Record */
            record: {
                [key: string]: unknown;
            };
        };
        /** TopN */
        TopN: {
            /** Categories Total */
            categories_total: number;
            /** Limit */
            limit: number;
        };
        /** TrialSummary */
        TrialSummary: {
            /** Brief Title */
            brief_title: string;
            /** Conditions */
            conditions: string[];
            /** Overall Status */
            overall_status: string;
            /** Phase */
            phase: string;
            /** Sponsor Name */
            sponsor_name: string;
            /** Start Date */
            start_date: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VisualizeRequest
         * @description The `POST /api/visualize` body (SCHEMAS.md §1). Only `query` is required.
         */
        VisualizeRequest: {
            /** Condition */
            condition?: string | null;
            /** Country */
            country?: string | null;
            /** Drug Name */
            drug_name?: string | null;
            /** End Year */
            end_year?: number | null;
            /** Query */
            query: string;
            /** Sponsor */
            sponsor?: string | null;
            /** Start Year */
            start_year?: number | null;
            trial_phase?: components["schemas"]["Phase"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    stored_trial_api_trials__nct_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nct_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredTrial"];
                };
            };
            /** @description The trial is not in the cache */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    visualize_api_visualize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisualizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"] | components["schemas"]["ClarificationResponse"] | components["schemas"]["NoResultsResponse"] | components["schemas"]["DegradedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description ClinicalTrials.gov or the LLM failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
}
